product_list:
  path: /{page}
  controller: App\Controller\ProductController::list
  requirements:
    page: '\d+'
  defaults:
    page: 1

product_show:
  path: /{slug}
  controller: App\Controller\ProductController::show
  requirements:
    page: '[\S]+'