product_list:
  path: /list
  controller: App\Controller\ProductController::list

product_show:
  path: /show/{slug}
  controller: App\Controller\ProductController::show
  requirements:
    page: '[\S]+'

add_cart_product:
  path: /add/{id}
  controller: App\Controller\ProductController::addCartProduct
  requirements:
    id: '\d+'

edit_product:
  path: /editProduct/{id}
  controller: App\Controller\ProductController::editProduct
  requirements:
    id: '\d+'

edit_category:
  path: /editCategory/{id}
  controller: App\Controller\ProductController::editCategory
  requirements:
    id: '\d+'

create_product:
  path: /createProduct/
  controller: App\Controller\ProductController::createProduct

log_out:
  path: /logOut
  controller: App\Controller\ProductController::logOut